title: <p align="center"> Raina Sharma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/raina-sharma-87451227/">LinkedIn</a> |
  <a href="https://github.com/rainasharma">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Working in Adobe Systems  for 6 years.
  <br>
  </p>



theme: jekyll-theme-minimal